### ISSUE TITLE
Publish docs on pursuit

### ISSUE THREAD

**Issue by safareli** [natefaubion/purescript-argparse-basic#1]
Would be nice if docs were published on pursuit

**Comment by artemisSystem** [comment]
I attempted to do this today, but ran into a roadblock. The `spago.dhall` is missing `license` and `repository` keys, there is no `bower.json` file, and the package isn't in the registry. I believe all these things are necessary before the package can be published to pursuit.

**Comment by thomashoneyman** [comment]
https://pursuit.purescript.org/packages/purescript-argparse-basic/2.0.0
